image: openjdk:17

before_script:
  - apt-get update -y
  ## gnupg2 for apt-key add
  - apt-get install -y --allow-unauthenticated gnupg2
  ## Install SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
  - apt-get update -y
  - apt-get install --allow-unauthenticated -y sbt
  - sbt sbtVersion

test:
  script:
    - sbt clean checkall +test
