language: scala
scala:
   - 2.11.12
   - 2.12.7
jdk:
  - oraclejdk11

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/.coursier/cache

script: "sbt clean checkall coverage test"
after_success: "sbt coverageReport coveralls"
