language: scala
scala:
   - 2.12.10
jdk:
  - oraclejdk17

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/.coursier/cache

script: "sbt clean checkall +test"
after_success: "sbt coverageReport coveralls"
